[package]
name = "root-finder"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
futures-util = { workspace = true }
nvimx = { workspace = true }

[lints]
workspace = true
