[package]
name = "nomad2"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
futures-util = { workspace = true }
nomad-macros = { path = "./macros" }
serde = { workspace = true }

[lints]
workspace = true
