[package]
name = "tracing-subscriber"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
home = { version = "0.5" }
tracing = { version = "0.1" }
tracing-appender = { version = "0.2" }
tracing-subscriber = { version = "0.3", features = ["fmt"] }
