[package]
name = "nomad"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
common = { workspace = true }
nvim-oxi = { workspace = true }
serde = { workspace = true }
serde_path_to_error = "0.1"
thiserror = { workspace = true }
tracing = { workspace = true }
