name: Release Stable

on:
  push:
    tags:
      # On every push of a semver-formatted tag (with no pre-release label).
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Verify that the tag's version matches the workspace's version
        uses: ./.github/actions/verify-tag-version-matches-workspace

  release-stable:
    needs: setup
    uses: ./.github/workflows/build-and-release.yaml
    secrets: inherit
    with:
      checkout-ref: ${{ github.ref_name }}
      is-stable: true
      release-name: "Nomad ${{ github.ref_name }}"
      release-body: "TODO"
      release-tag: ${{ github.ref_name }}
